I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 70, in script
    n "hola"
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "game/script.rpy", line 13, in execute
    screen stamina():
  File "game/script.rpy", line 13, in execute
    screen stamina():
  File "game/script.rpy", line 15, in execute
    frame:
  File "game/script.rpy", line 20, in execute
    vbar value StaticValue(n, 3, 0.5): #bar_invert True
  File "game/script.rpy", line 20, in keywords
    vbar value StaticValue(n, 3, 0.5): #bar_invert True
  File "game/script.rpy", line 20, in <module>
    vbar value StaticValue(n, 3, 0.5): #bar_invert True
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 70, in script
    n "hola"
  File "C:\renpy-7.4.4-sdk\renpy\ast.py", line 898, in execute
    statement_name(stmt_name)
  File "C:\renpy-7.4.4-sdk\renpy\ast.py", line 47, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "C:\renpy-7.4.4-sdk\renpy\exports.py", line 1758, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 2978, in do_with
    return self.interact(trans_pause=True,
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 4055, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "C:\renpy-7.4.4-sdk\renpy\display\screen.py", line 476, in visit_all
    callback(self)
  File "C:\renpy-7.4.4-sdk\renpy\display\core.py", line 4055, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\renpy-7.4.4-sdk\renpy\display\screen.py", line 487, in per_interact
    self.update()
  File "C:\renpy-7.4.4-sdk\renpy\display\screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 13, in execute
    screen stamina():
  File "game/script.rpy", line 13, in execute
    screen stamina():
  File "game/script.rpy", line 15, in execute
    frame:
  File "game/script.rpy", line 20, in execute
    vbar value StaticValue(n, 3, 0.5): #bar_invert True
  File "game/script.rpy", line 20, in keywords
    vbar value StaticValue(n, 3, 0.5): #bar_invert True
  File "game/script.rpy", line 20, in <module>
    vbar value StaticValue(n, 3, 0.5): #bar_invert True
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
The Fear v1 1.0
Wed Jan 24 17:58:11 2024
